### ISSUE TITLE
Unknown column 'c_enc_key' in 'field list'

### ISSUE THREAD

**Issue by xenos1337** [FinGu/c_auth#13]
I'm getting this error 

`Fatal error: Uncaught Exception: Unknown column 'c_enc_key' in 'field list' in G:\test\functions\general\mysqli_wrapper.php:44 Stack trace: #0 G:\test\functions\api\admin\var.php(41): mysqli_wrapper->query('INSERT INTO c_p...', Array) #1 G:\test\dashboard\vars.php(29): api\admin\create_var(Object(mysqli_wrapper), 'psKyKo7G4zpEjR7...', 'test', 'HE9qEpjdvI1+3y0...') #2 {main} thrown in G:\test\functions\general\mysqli_wrapper.php on line 44`

when I'm trying to make a new var at http://localhost:8460/dashboard/vars.php with var_name=test&var_value=test&create_var=

is this a problem with the encryption?

**Comment by xenos1337** [comment]
nvm had to add c_enc_key to database lmao

**Comment by FinGu** [comment]
https://github.com/FinGu/c_auth/commit/7d77d7d5c8281f149cbca6d56571047fd1aaed09
