### ISSUE TITLE
X Undeclared identifier 

### ISSUE THREAD

**Issue by LionHackerman** [FinGu/c_auth#4]
![yes](https://user-images.githubusercontent.com/58070003/116773673-2a855a00-aa9a-11eb-9894-a192b07eb263.PNG)
VS errors ^

**Comment by LionHackerman** [comment]
C++ Example, I included (curl, cryptopp, etc)

**Comment by FinGu** [comment]
My bad, rename all ‘x’s to ‘value’

**Comment by LionHackerman** [comment]
Thanks buddy
